Сделал это это и вот это
DanilShum/autocomplete pull request #11
Opened 2020-04-20 06:50 UTC by DanilShum

2020-04-20 08:07 UTC, web-crab reviewed
<img width="466" alt="image" src="https://user-images.githubusercontent.com/19954244/79723363-4a623980-82ee-11ea-9d86-98dcf46ed508.png">

когда инпут сфокусирован - ховер стили не должны срабатывать

<img width="369" alt="image" src="https://user-images.githubusercontent.com/19954244/79728670-f576f100-82f6-11ea-8e91-c1372c7f527e.png">

задай для всего шрифт sans-serif, для инпутов и баттонов нужно шрифт указывать явно, так как он не наследуется от body

2020-04-20 08:07 UTC, web-crab commented on index.html
> +                            <div class="search__arrow-wrapper ">
а зачем дополнительный див для стрелочки?

2020-04-20 08:07 UTC, web-crab commented on index.html
> +                    <div class="search__section">
зачем дополнительный див? label должно быть достаточно

2020-04-20 08:07 UTC, web-crab commented on index.html
> +                    <div class="search__section">
ему нужно установить display block, а то он по умолчанию inline

2020-04-20 08:07 UTC, web-crab commented on index.html
> +            <div class="search__wrapper">
зачем эти два дива?

2020-04-20 08:07 UTC, web-crab commented on style.css
> +    padding: 20px -40px;
отрицательный паддинг?)

2020-04-20 08:07 UTC, web-crab commented on style.css
> +    display: flex;
зачем флекс?

2020-04-20 08:07 UTC, web-crab commented on style.css
> +    text-align: center;
а че центр?

2020-04-20 08:07 UTC, web-crab commented on style.css
> +    transition: .3s ease-in-out;
.3 долго
ease-in, ease-out, ease-in-out применяют только для transform

2020-04-20 08:07 UTC, web-crab commented on style.css
> +    width: 650px;
<img width="720" alt="image" src="https://user-images.githubusercontent.com/19954244/79724171-c14c0200-82ef-11ea-8086-75db291b5562.png">
а зачем маргины?

2020-04-20 08:07 UTC, web-crab commented on style.css
> +.search__input:not(:placeholder-shown) + .search__action {
🔥

2020-04-20 08:07 UTC, web-crab commented on style.css
> +    transition: .3s ease-in-out;
.3s тоже долго, тут манюсенькая анимашка.
 а вот ease-in-out правильно подобрал

2020-04-20 08:07 UTC, web-crab commented on style.css
> +    background: #ccc;
а зачем двоим элементам менять бг? они ж друг на друге лежат. достаточно одному менять

2020-04-20 08:07 UTC, web-crab commented on style.css
> +    z-index: 999;
z-index: 1 достаточно)

2020-04-20 08:07 UTC, web-crab commented on style.css
> +    transition: 0.5s;
опять transition? уже указывал для него.
0.5 это ооочень долго для такого. и лучше в transition указывать для какого свойства применять. чтобы только оно анимировалось.
`transition: transform 0.2s;`

2020-04-20 08:07 UTC, web-crab commented on style.css
> +    cursor: pointer;
зачем pointer?

2020-04-20 08:07 UTC, web-crab commented on style.css
> +    color: rgb(80, 110, 245) !important;
старайся организовывать стили так, чтобы не юзать `!important`

2020-04-20 08:07 UTC, web-crab commented on style.css
> +    border: 10px solid transparent;
крупноватая стрелка, 6-8px должно быть достаточно

2020-04-20 08:07 UTC, web-crab commented on style.css
> +    transition: .3s ease-in-out;
тоже долго

2020-04-20 08:07 UTC, web-crab commented on style.css
> +    transition: .3s ease-in-out;
задублировал transition

2020-04-20 08:07 UTC, web-crab commented on style.css
> +    border-bottom: 0;
задублировал border: 0

2020-04-20 08:07 UTC, web-crab commented on index.html
> +                <div class="search__listing-wrapper">
для чего доп обертка?

2020-04-20 08:07 UTC, web-crab commented on style.css
> +    width: 0;
полностью лишний блок

2020-04-20 08:07 UTC, web-crab commented on style.css
> +.search__listing-wrapper:active {
для чего :active?

2020-04-20 08:07 UTC, web-crab commented on style.css
> +    overflow-y: scroll;
лучше использовать `overflow-y: auto`, тогда скроллбар будет показываться только когда элементы не влезают

2020-04-20 08:14 UTC, DanilShum commented on style.css
> +.search__listing-wrapper:active {
> для чего :active?

Если убрать :active , то при нажатии по списку с input сразу пропадает фокус и список закрывается, при этом ничего не вставляется строку

2020-04-20 08:18 UTC, DanilShum commented on style.css
> +    background: #ccc;
они разных размеров, и вот что получается если задать только section-у
![image](https://user-images.githubusercontent.com/58886644/79729824-a0d47580-82f8-11ea-9deb-005c9eb64433.png)

2020-04-20 09:15 UTC, web-crab commented on style.css
> +    background: #ccc;
input {
  background-color: transparent
}

2020-04-20 09:17 UTC, web-crab commented on style.css
> +.search__listing-wrapper:active {
обрабатывай mousedown вместо click на лишках, тогда preventDefault отменит потерю скролла

2020-04-20 09:18 UTC, web-crab requested changes

2020-04-20 09:18 UTC, web-crab commented on autocmplete.js
> +        if (this) {
this всегда будет в любом месте кода, зачем его проверять?)

2020-04-21 12:14 UTC, web-crab requested changes

2020-04-21 12:14 UTC, web-crab commented on style.css
> +    transition: .2s;
нужно указывать для какого свойства transition, чтобы не все свойства анимировались

2020-04-21 12:14 UTC, web-crab commented on style.css
> +    transition: .2s;
тоже нужно указать для чего

2020-04-21 12:14 UTC, web-crab commented on style.css
> +    transition: transform .1s ease-in-out, border-top-color .1s ease-in-out;
два раза не нужно указывать `transition`, css тебя с первого раза понял)

2020-04-21 12:14 UTC, web-crab commented on style.css
> +    height: 400px;
лучше указать max-height, тогда не будет белой пустыни внизу, когда мало вариантов

2020-04-21 12:14 UTC, web-crab commented on style.css
> +    transition: transform .2s ease-in-out, color .2s ease-in-out;
и тут задвоил transition, его нужно указывать для элемента в состоянии покоя, а не на :hover, :focus и тд

2020-04-21 12:34 UTC, web-crab approved these changes

2020-04-21 12:35 UTC, merged